### ISSUE TITLE
Write new test cases in CCV

### ISSUE THREAD

**Issue by Sital999** [cardanoapi/cardano-constitution-voting-app#28]
Add new test cases for:
- [x] % Approval to replace Approved/ Not Approved [#133](https://github.com/ClearContracts/cardano-constitution-voting-app/issues/133)
- [x] Voters should be stacked horizontally [#143](https://github.com/ClearContracts/cardano-constitution-voting-app/issues/143)
- [x] Create Poll has input for URL field and Hash field [#145](https://github.com/ClearContracts/cardano-constitution-voting-app/issues/145)
- [x] Platform Fails to Update Wallet and Role After Switching Wallets in Extension [#127](https://github.com/ClearContracts/cardano-constitution-voting-app/issues/127)
